// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { withTimeout } from '@/lib/async-timeout'

const SESSION_LOOKUP_TIMEOUT_MS = 2_500

function findSession(value: unknown): { access_token: string; expires_at?: number } | null {
  if (!value || typeof value !== 'object') return null
  const record = value as Record<string, unknown>
  if (typeof record.access_token === 'string') {
    return {
      access_token: record.access_token,
      expires_at: typeof record.expires_at === 'number' ? record.expires_at : undefined,
    }
  }
  if (record.currentSession) return findSession(record.currentSession)
  if (record.session) return findSession(record.session)
  return null
}

function readCachedAccessToken(): string | null {
  if (typeof window === 'undefined') return null
  try {
    const nowSec = Math.floor(Date.now() / 1000)
    for (let i = 0; i < window.localStorage.length; i += 1) {
      const key = window.localStorage.key(i)
      if (!key || !key.startsWith('sb-') || !key.endsWith('-auth-token')) continue
      const raw = window.localStorage.getItem(key)
      if (!raw) continue
      const session = findSession(JSON.parse(raw))
      if (!session) continue
      // Skip expired tokens — attaching an expired bearer is worse than
      // attaching none (the server rejects, and we miss the chance to let
      // supabase-js auto-refresh on the next getSession() tick).
      if (session.expires_at && session.expires_at <= nowSec) continue
      return session.access_token
    }
  } catch {
    return null
  }
  return null
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // Read the cached token synchronously from localStorage first.
    // Supabase's getSession() can resolve with `null` on the very first
    // call after a navigation/hard refresh because the in-memory session
    // hasn't been rehydrated from storage yet. If we trusted that null,
    // protected server fns would 401 on first navigation and only succeed
    // after a manual refresh. The cached token is the source of truth
    // until getSession resolves with a real session.
    const cachedToken = readCachedAccessToken()
    const liveToken = await withTimeout(
      supabase.auth.getSession().then(({ data }) => data.session?.access_token ?? null),
      SESSION_LOOKUP_TIMEOUT_MS,
      'Server function auth token lookup timed out',
    ).catch((error) => {
      console.warn('[server-fn-auth] token lookup failed; using cached token if available', error)
      return null
    })
    const token = liveToken ?? cachedToken
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
